config/routes.rb
Rails.application.routes.draw do
  get 'courses/index'

  get 'greeter/hello' => "greeter#hello"
  get 'greeter/goodbye'

  root 'courses#index'

end

app/models/coursera.rb
class Coursera
	include HTTParty

	base_uri 'https://api.coursera.org/api/catalog.v1/courses'
	default_params fields: "smallIcon,shortDescription", q: "search"
	format :json

	def self.for term
		get("",query: {query: term})["elements"]
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  def index
  	@search_term = params[:looking_for] || 'jhu'
  	@courses = Coursera.for(@search_term) #|| [] # you can give an empty list
  end
end

app/controllers/greeter_controller.rb
class GreeterController < ApplicationController

  #def hello
  #end

  #def goodbye
  #end

  def hello
  	random_names =["Alex", "Joe", "Michael"]
  	@name = random_names.sample
  	@time = Time.now
  	@times_displayed ||= 0
  	@times_displayed += 1
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/greeter_helper.rb
module GreeterHelper

	def formatted_time(time)
		#time string in AM/PM format
		time.strftime("%I:%M%p")
	end
	
end

app/views/courses/index.html.erb
<h1>Searching for - <%= @search_term%></h1>

<% if @courses.nil? %>
	<p>No courses found with relevant information...Sorry</p>
<% else %>
	<table border="1">
		<tr>
			<td>Image</td>
			<td>Name</td>
			<td>Description</td>
		</tr>
		<% @courses.each do |course|%>
			<tr class=<%=cycle('even', 'odd')%>>
				<td><%= image_tag(course["smallIcon"])%></td>
				<td><%= course["name"]%></td>
				<td><%= course["shortDescription"]%></td>
			</tr>
		<% end %>
	</table>
<% end %>

app/views/greeter/hello.html.erb
<--! Previous code

<% random_names = ["Alex", "Joe", "Michael"] %>
<h1>Greetings, <%= random_names.sample %></h1>
<p>The time now is <%= Time.now %></p>

<h1>Greetings, <%= @name %></h1>
<p>The time now is <%= @time %></p>
<p>The page has been viewed <%= @times_displayed %> time(s)</p>

!-->

<h1>Greetings, <%= @name %></h1>
<p>The time now is <%= formatted_time(@time) %></p>
<p>The page has been viewed <%= @times_displayed %> time(s)</p>

<p><%= link_to "Google", "http://www.google.com" %></p>
<p><%= link_to "Goodbye", greeter_goodbye_path%></p>
 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CourseraMod3App</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>